name: pull request preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run prebuild script
        run: ./prebuild.sh
      - name: Build core
        run: yarn core:build
      - name: Build web
        run: yarn web:build --base /pgv
      - name: Upload production artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./packages/web/dist
  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: .
      - name: Inspect
        run: ls -al
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy preview to GitHub Pages
        id: deployment
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: main
          umbrella-dir: pr-preview
          action: auto
